### ISSUE TITLE
Documentation Required

### ISSUE THREAD

**Issue by neubig** [odashi/mteval#1]
Currently there is no documentation showing how to use mteval.
Specifically, it would be nice to have a description of the strings that can be given to the "-e" option.

**Comment by odashi** [comment]
OK, I'll prepare some documentations including their usage ASAP.

**Comment by odashi** [comment]
I've just added installation guide, usage, and metrics descriptions into README.md.

**Comment by neubig** [comment]
Thanks! That's really helpful.
