### ISSUE TITLE
BLEUが0になる問題

### ISSUE THREAD

**Issue by takegue** [odashi/mteval#3]
ref : This is a . 
hyp: This is a test .
に対して  ツールの mteval-sentence でBLEUを計算すると
BLEUが0になる問題(正確には0.537285)が発生するのですが,  何か対処策はありますでしょうか？

**Comment by odashi** [comment]
スムージングなしのBLEUの場合、正確な値は0です（4-gramの一致がないため）
スムージングを行いたい場合は -e BLEU:smooth=1 などと指定して下さい（数字を変えるとスムージングの強さも変わります）。算出される値についてはスムージング手法により異なるので正確な値というのはありません。
